USE [master]
GO

/****** Object:  Database [c3]    Script Date: 11/10/2020 12:32:02 PM ******/
CREATE DATABASE [c3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'c3_Data', FILENAME = N'F:\sqldata\c3\c3.mdf' , SIZE = 3760960KB , MAXSIZE = UNLIMITED, FILEGROWTH = 204800KB )
 LOG ON 
( NAME = N'c3_Log', FILENAME = N'E:\sqllog\c3\c3.ldf' , SIZE = 8257024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
GO

ALTER DATABASE [c3] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [c3].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [c3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [c3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [c3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [c3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [c3] SET ARITHABORT OFF 
GO

ALTER DATABASE [c3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [c3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [c3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [c3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [c3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [c3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [c3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [c3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [c3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [c3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [c3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [c3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [c3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [c3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [c3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [c3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [c3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [c3] SET RECOVERY FULL 
GO

ALTER DATABASE [c3] SET  MULTI_USER 
GO

ALTER DATABASE [c3] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [c3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [c3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [c3] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [c3] SET  READ_WRITE 
GO

